In [15]:
import pandas as pd

ib3=pd.read_csv('n_3big.csv')
ib3

    Unnamed: 0  Index   Fitness    cum_sum  cum_perc
0            0    0.0  0.228546   0.228546       1.0
1            1    1.0  0.228546   0.457091       2.0
2            2    2.0  0.228546   0.685637       3.0
3            3    3.0  0.228546   0.914182       4.0
4            4    4.0  0.228546   1.142728       5.0
..         ...    ...       ...        ...       ...
95          95   95.0  0.228546  21.940373      96.0
96          96   96.0  0.228546  22.168918      97.0
97          97   97.0  0.228546  22.397464      98.0
98          98   98.0  0.228546  22.626010      99.0
99          99   99.0  0.228546  22.854555     100.0

[100 rows x 5 columns]